version: "3"

vars:
  APP_NAME: arko
  BUILD_DIR: build/bin
  MOBILE_PKG: github.com/arko-chat/arko/cmd/mobile
  ANDROID_LIBS_DIR: mobile/android/app/libs
  IOS_BUILD_DIR: build/ios

dotenv: [".env"]

tasks:
  default:
    desc: List available tasks
    cmds:
      - go tool task --list

  setup:
    desc: Install dev tooling
    cmds:
      - go mod tidy
      - cd frontend && bun install

  setup:mobile:
    desc: Install gomobile tooling
    cmds:
      - go install golang.org/x/mobile/cmd/gomobile@latest
      - go install golang.org/x/mobile/cmd/gobind@latest
      - gomobile init

  generate:
    desc: Generate templ files
    sources:
      - "**/*.templ"
    cmds:
      - go tool templ generate

  dev:
    desc: Run dev mode (Vite + Go with hot reload)
    deps:
      - dev:vite
      - dev:go

  dev:vite:
    internal: true
    dir: frontend
    cmds:
      - bun run vite dev

  dev:go:
    internal: true
    cmds:
      - sleep 2
      - "go tool wgo -file .go -file .templ -xfile _templ.go go tool templ generate :: go run -tags dev,goolm ./cmd/arko {{.CLI_ARGS}}"

  build:frontend:
    desc: Build frontend assets
    dir: frontend
    cmds:
      - bun run vite build
    sources:
      - src/**/*
      - vite.config.*
      - postcss.config.*
    generates:
      - ../components/assets/dist/**/*

  build:
    desc: Build production binary
    deps:
      - generate
      - build:frontend
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - >
        go build
        -tags=goolm
        -ldflags="-s -w -X main.version={{.VERSION}}"
        -o {{.BUILD_DIR}}/{{.APP_NAME}}
        ./cmd/arko
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"

  build:wasm:
    desc: Build WASM
    deps:
      - generate
      - build:frontend
    cmds:
      - mkdir -p {{.BUILD_DIR}}/wasm
      - >
        GOOS=js
        GOARCH=wasm
        GOTOOLCHAIN=go1.25.7
        go build
        -tags=goolm
        -ldflags="-X main.version={{.VERSION}}"
        -o {{.BUILD_DIR}}/wasm/{{.APP_NAME}}.wasm
        ./cmd/mobile
      - cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" "{{.BUILD_DIR}}/wasm/"
      - echo "WASM written to {{.BUILD_DIR}}/wasm/{{.APP_NAME}}.wasm"

  build:android:
    desc: Build Android AAR and copy to Android project
    deps:
      - generate
      - build:frontend
    cmds:
      - mkdir -p {{.ANDROID_LIBS_DIR}}
      - >
        gomobile bind
        -tags=goolm
        -target=android
        -androidapi=24
        -o {{.ANDROID_LIBS_DIR}}/mobile.aar
        {{.MOBILE_PKG}}
      - echo "AAR written to {{.ANDROID_LIBS_DIR}}"

  build:ios:
    desc: Build iOS xcframework and copy to Xcode project
    deps:
      - generate
      - build:frontend
    cmds:
      - mkdir -p {{.IOS_BUILD_DIR}}
      - >
        gomobile bind
        -tags=goolm
        -target=ios
        -o {{.IOS_BUILD_DIR}}/Mobile.xcframework
        {{.MOBILE_PKG}}
      - echo "xcframework written to {{.IOS_BUILD_DIR}}"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.IOS_BUILD_DIR}}
      - rm -rf components/assets/dist
      - find . -name "*_templ.go" -delete

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - go tool templ generate
      - go build ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... {{.CLI_ARGS}}
